
package com.ws.banque.wsClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://service.banque.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToDh", targetNamespace = "http://service.banque.ws.com/", className = "com.ws.banque.wsClient.ConversionEuroToDh")
    @ResponseWrapper(localName = "conversionEuroToDhResponse", targetNamespace = "http://service.banque.ws.com/", className = "com.ws.banque.wsClient.ConversionEuroToDhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param numero
     * @return
     *     returns com.ws.banque.wsClient.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service.banque.ws.com/", className = "com.ws.banque.wsClient.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service.banque.ws.com/", className = "com.ws.banque.wsClient.GetCompteResponse")
    public Compte getCompte(
        @WebParam(name = "numero", targetNamespace = "")
        String numero);

    /**
     * 
     * @return
     *     returns java.util.List<com.ws.banque.wsClient.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListeComptes", targetNamespace = "http://service.banque.ws.com/", className = "com.ws.banque.wsClient.GetListeComptes")
    @ResponseWrapper(localName = "getListeComptesResponse", targetNamespace = "http://service.banque.ws.com/", className = "com.ws.banque.wsClient.GetListeComptesResponse")
    public List<Compte> getListeComptes();

}
